### ISSUE TITLE
Synthesizer didn't terminate

### ISSUE THREAD

**Issue by masaomi-yamaguchi** [jfeser/L2#5]
I tried to synthesize
`dune exec l2 synth bench/concat.json`
,which is the motivation example in their paper, didn't terminate.
(I am not sure the above command is correct because the command in README is not available in the current implementation.)

I used following commands to build with opam 0.2.5:
```
git clone git@github.com:jfeser/L2.git; cd L2
opam switch create 4.06.1
eval $(opam env)
opam install --deps-only ./l2.opam.locked
dune build
```

Could you check whether it is a problem with my usage or build?

**Comment by jfeser** [comment]
Hi,

If you'd like to reproduce the results from the paper, use the pldi-modernize branch of the repository. Running `dune exec src/l2.exe -- benchmarks/concat.json` should give the expected behavior on this branch.

The version on the master branch is more general, but slower and probably has some bugs.
